### ISSUE TITLE
Add image deletion support for Docker registry v2

### ISSUE THREAD

**Issue by brennerm** [brennerm/docker-registry-frontend#8]

**Comment by pavlovpetro** [comment]
In order to enable deletion support you have to add in the section "storage" of the file "config.yml" following instruction:
```
delete:
    enabled: true
```
For example:
```
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry     
  delete:
    enabled: true
```
